### ISSUE TITLE
Readme should account for MacOS and Windows differences

### ISSUE THREAD

**Issue by barona-mika-vilpas** [catppuccin/lazygit#11]
Hi, I noticed lazygit has different paths for the configuration file depending on the operating system:

```
Default path for the config file:

- Linux: ~/.config/lazygit/config.yml
- MacOS: ~/Library/Application Support/lazygit/config.yml
- Windows: %APPDATA%\lazygit\config.yml
```
https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

No big issue for me, but perhaps the instructions could indicate the path may be different from the default Linux path, which is used now.

**Comment by nekowinston** [comment]
Just a note here, this is the same case as https://github.com/catppuccin/k9s/pull/2, the technically correct README here would be

Linux:
`"${XDG_CONFIG_HOME:-$HOME/.config}/lazygit"`
macOS:
`"${XDG_CONFIG_HOME:-$HOME/Library/Application Support}/lazygit"`
