### ISSUE TITLE
No effect after changing config.yml

### ISSUE THREAD

**Issue by Dante983** [catppuccin/lazygit#13]
Hello,

As the title suggests, I don't see any changes when i update config.yml file.
I am using macos and file exists, bot no changes happend, no error or anything.
It's probably something dumb, but here I am :D

**Comment by nullishamy** [comment]
What does `lazygit --print-config-dir` give you, and what is your config file at the minute.

**Comment by Dante983** [comment]
/Users/userName/Library/Application Support/lazygit

**Comment by Dante983** [comment]
> What does `lazygit --print-config-dir` give you, and what is your config file at the minute.

/Users/userName/Library/Application Support/lazygit

**Comment by nullishamy** [comment]
You need the `gui` field as the root.
