### ISSUE TITLE
Some colors seem to be off

### ISSUE THREAD

**Issue by bezlant** [catppuccin/lazygit#5]
I've tested it an seems to be working somewhat, but when I'm trying to commit a specific line the line of the text selected and the background are the same, so I can't see which line I'm on.
The option responsible for this seems to be selectedRangeBgColor, I had to keep it blue otherwise I can't see the active line.

**Comment by bezlant** [comment]
I've tested it an seems to be working somewhat, but when I'm trying to commit a specific line the line of the text selected and the background are the same, so I can't see which line I'm on.
The option responsible for this seems to be     selectedRangeBgColor, I had to keep it blue otherwise I can't see the active line.

**Comment by nullishamy** [comment]
I'm not entirely sure what's going on here. Perhaps a terminal specific issue? Here's mine with WezTerm 
![image](https://github.com/catppuccin/lazygit/assets/99221043/4d3c8070-19f8-41a1-a5a1-3f6304dd9fb0)

It's surface0 as expected, is this what you are referring to?

**Comment by nullishamy** [comment]
Just thought I should mention this. I was not experiencing your issue, but I recently upgraded my system, and now see the wrong colours! I can now fix this easily because I have local repro.

**Comment by nullishamy** [comment]
Take a look at #9, should resolve your problems!
