### ISSUE TITLE
Some `theme` options have changed upstream

### ISSUE THREAD

**Issue by xfzv** [catppuccin/lazygit#8]
As discussed in [#5](https://github.com/catppuccin/lazygit/issues/5#issuecomment-1697766848)

---

[The current LazyGit config](https://github.com/jesseduffield/lazygit/blob/2b26b380b6ac40d3acfbf0446237990c11e5e0d2/docs/Config.md?plain=1#L46-L68) has some colors options that differ from those used in Catppuccin themes.

- `searchingActiveBorderColor` - added in https://github.com/jesseduffield/lazygit/commit/9df634f13f6dd8f1e766e81c8ad2ff036df8fe20 - Jul 3, 2023
- `defaultFgColor` - added in https://github.com/jesseduffield/lazygit/commit/f96246c03806e5de512a6e32777418ed2345d00d - Nov 26, 2022
- `lightTheme` - removed in https://github.com/jesseduffield/lazygit/pull/2257/commits/1ac3ae1ad1b904a02e12d49adec0197e6067006e - Nov 12, 2022

https://github.com/catppuccin/lazygit/blob/b2ecb6d41b6f54a82104879573c538e8bdaeb0bf/themes/frappe.yml#L1-L19

https://github.com/catppuccin/lazygit/blob/b2ecb6d41b6f54a82104879573c538e8bdaeb0bf/themes/latte.yml#L1-L19

https://github.com/catppuccin/lazygit/blob/b2ecb6d41b6f54a82104879573c538e8bdaeb0bf/themes/macchiato.yml#L1-L19

https://github.com/catppuccin/lazygit/blob/b2ecb6d41b6f54a82104879573c538e8bdaeb0bf/themes/mocha.yml#L1-L19

**Comment by nullishamy** [comment]
Cool, thanks for opening! I plan on doing some sort of versioning in the repo to handle these cases, if they are breaking.

**Comment by nullishamy** [comment]
These should be fixed in #9.
